#!/bin/bash
# Software License Agreement (BSD)
#
# Author    Mike Purvis <mpurvis@clearpathrobotics.com>
# Copyright (c) 2014-2016, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
# * Redistributions of source code must retain the above copyright notice, this list of conditions and the
#   following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or
#   promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

ROS_DISTRO=${ROS_DISTRO:-lunar}
ROS_CONFIGURATION=${ROS_CONFIGURATION:-desktop_full}
ROS_EXTRA_PACKAGES=${ROS_EXTRA_PACKAGES:-}
ROS_INSTALL_DIR=${ROS_INSTALL_DIR:-/opt/ros/${ROS_DISTRO}}

do_install()
{
  set -e
  export CMAKE_PREFIX_PATH=$(brew --prefix qt5)
  export PATH=$(pwd)/shim:$PATH

  WS=${ROS_DISTRO}_${ROS_CONFIGURATION}_ws
  cd $WS

  # if [ -d ${ROS_INSTALL_DIR} ]; then
  #   rm -rf ${ROS_INSTALL_DIR}/*
  # else
  #   echo "This sudo prompt is to create and chown ${ROS_INSTALL_DIR}."
  #   sudo mkdir -p ${ROS_INSTALL_DIR}
  #   sudo chown $USER ${ROS_INSTALL_DIR}
  # fi

  catkin config --install \
    --install-space ${ROS_INSTALL_DIR} \
    --cmake-args \
      -DCATKIN_ENABLE_TESTING=1 \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_FIND_FRAMEWORK=LAST \
      -DCATKIN_ENABLE_TESTING=0 \
      -DPYTHON_EXECUTABLE=$(which python2) \
      -DPYTHON_LIBRARY=$(python2 -c "import sys; print sys.prefix")/lib/libpython2.7.dylib \
      -DPYTHON_INCLUDE_DIR=$(python2 -c "import sys; print sys.prefix")/include/python2.7

  catkin build --limit-status-rate 1 

  echo "Installation successful, please source the ROS workspace:"
  echo
  echo "  source ${ROS_INSTALL_DIR}/setup.bash"
  echo
  
  # Check for SIP if on OSX/macOS 10.11 (El Capitan) or later
  if [[ `sw_vers -productVersion` > "10.10" ]]
  then
    if `csrutil status | grep -q enabled`
    then
      echo "You have System Integrity Protection enabled."
      echo
      echo "This prevents DYLD_LIBRARY_PATH from being exported to subshells"
      echo "Please add: export DYLD_LIBRARY_PATH=\$DYLD_LIBRARY_PATH:/opt/ros/\$ROS_DISTRO/lib"
      echo "To the start of /opt/ros/$ROS_DISTRO/bin/rosrun to work around the issue."
    fi
  fi
}

do_install
